### PR TITLE
Detail `Accept-Post` header to be on `OPTIONS` responses.

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/fcrepo/fcrepo-specification/issues/308

### CODE REVIEW

**Comment by awoods** [comment]
Note: After reviewing the LDP specification further and considering the complexity of adding `SHOULD` for `Accept-Post` headers on `GET` responses for LDPC's but not LDPCv's, I believe it is cleanest to simply add the point of clarification in the `3.9 External Binary Content` section that `Accept-Post` is to be found in responses to `OPTIONS` requests.

**Review by escowles — APPROVED** [review]

**Comment by zimeon** [comment]
Apologies but I have questions back up on #308...

**Review by escowles — CHANGES_REQUESTED** [review]
Given ongoing discussion, I think we should close this PR in favor of pursuing #338

**Comment by awoods** [comment]
Closing in favor of direction discussed in https://github.com/fcrepo/fcrepo-specification/issues/338

**Pull request closed without merging**
