### PR TITLE
Clarifying optionality of server-managed versioning for LDPRv

### LINKED ISSUE #231: Server-managed versioning required?
4.1.3.1 Versioned Resources / PUT / General says:
> An LDPRv may support PUT. An implementation receiving a PUT request for an LDPRv must both correctly respond as per [LDP] as well as create a new LDPRm contained in an appropriate LDPCv.

That sounds like we are requiring server-managed versioning when an LDPR has versions and receives a PUT request.  Should we change that to:
> An LDPRv may support PUT. An implementation receiving a PUT request for an LDPRv must correctly respond as per [LDP] and may also create a new LDPRm contained in an appropriate LDPCv.

### PR DESCRIPTION
**Pull request by escowles**
Fixes #231

### CODE REVIEW

**Review by zimeon — CHANGES_REQUESTED** [review]
I think PATCH is currently inconsistent - suggests that the LDPRm is be version _before_ patch, whereas for POST/PUT we are suggesting the version _after_ the request (suggest "... the version of the LDPRv after modification by the PATCH request.").

I'm not really sure that this is the best strategy but we should be consistent, and it is only SHOULD

**Comment by escowles** [comment]
@zimeon I struggled a little with the exact wording, perhaps saying "...as modified by the [method]" would be clearer than "...that was modified by the [method]"?

**Comment by zimeon** [comment]
I think "as modified by" is better than "that was modified by" but still seems ambiguous to me. To make it really clear I can't think of options other than the form "... (after|resulting from|following|...) modification by"

**Comment by escowles** [comment]
@zimeon Yes, that's clearer — I've pushed a new commit that explicitly spells out that it's the state following the creation/modification.

**Review by zimeon — DISMISSED** [review]
Thanks @escowles

**Review by awoods — DISMISSED** [review]

**Review by dannylamb — DISMISSED** [review]
LGTM

**Pull request closed without merging**
