### PR TITLE
Fix auth/acl ns scheme

### PR DESCRIPTION
**Pull request by csarven**

### CODE REVIEW

**Comment by zimeon** [comment]
Hmm... if I dereference https://www.w3.org/ns/auth/acl I get a document that includes...
```
    @prefix acl: <http://www.w3.org/ns/auth/acl#> .
```

**Comment by csarven** [comment]
w3.org is making https available all across (AFAIK) and supports upgrading insecure requests. So, both http and https URLs of the same document is available. `http:` is the canonical scheme for the auth/acl ns.

**Comment by zimeon** [comment]
Yes, indeed! Sorry, I misread the PR as suggesting changing the ns to https: when in fact you are correcting it to http:. Completely agree

**Review by zimeon — APPROVED** [review]

**Review by awoods — APPROVED** [review]
Let's get this in before publishing the 1.0 spec.

**Comment by awoods** [comment]
I have published the 1.0 release with this change: https://fedora.info/spec/

We should merge this soon... although, in case there is any concern with including this PR, I will hold off on a community announcement until the merge has happened. I think the `https` to `http` update is non-controversial.

**Comment by csarven** [comment]
Please consider https://github.com/fcrepo/fcrepo-specification/pull/413#issuecomment-830141870 - if/when updates to references and other changes can be introduced.

**Review by dannylamb — APPROVED** [review]
sorry i missed this one

**Pull request merged**
