### PR TITLE
Change external-body 'type' to 'access-type'

### PR DESCRIPTION
**Pull request by awoods**
..per https://tools.ietf.org/html/rfc1521#section-7.3.3

### CODE REVIEW

**Review by barmintor — APPROVED** [review]
Thanks for catching this mistake, @awoods.

**Review by escowles — APPROVED** [review]

**Review by zimeon — APPROVED** [review]

**Comment by zimeon** [comment]
This change is good... but, related, is there are reason why we cite https://tools.ietf.org/html/rfc1521#section-7.3.3 instead of https://tools.ietf.org/html/rfc2046#section-5.2.3 that obsoletes it? (might also be nice to add the direct link to the section of the RFC after the normative bibliography link)

**Comment by awoods** [comment]
@zimeon : I will create a follow-on PR for updating the referenced spec and adding a direct link, so as not to hold up this PR.

**Comment by zimeon** [comment]
:+1:

**Pull request merged**
