### PR TITLE
Reword abstract; Resolves #24.

### LINKED ISSUE #24: What is "Fedora information architecture"?
The [Abstract](http://fcrepo.github.io/fcrepo-specification/#abstract)'s use of term "Fedora information architecture" is undefined/unlinked and doesn't appear elsewhere in the document. This ends up making the statement seem a bit circular. From a little searching I didn't come up with anything that looked like a definitive document (and did find old docs like https://arxiv.org/abs/cs/0501012 which presumably gives the wrong picture). I think it needs a reference or rewording.

### PR DESCRIPTION
**Pull request by ruebot**
See: #24 

Pull together what I see to be the resolution to #24. However, I could not tell whether or not we want a reference to [this](https://arxiv.org/abs/1312.1258) paper there as well.

@awoods @zimeon @ajs6f @acoburn

### CODE REVIEW

**Review by ajs6f — APPROVED** [review]
👍

**Review by acoburn — APPROVED** [review]
👍

**Comment by zimeon** [comment]
Belated :+1:

**Comment by awoods** [comment]
Better belated than benevered.

**Pull request merged**
