### PR TITLE
Change external-body support to SHOULD

### PR DESCRIPTION
**Pull request by acoburn**

### CODE REVIEW

**Comment by awoods** [comment]
It would seem that the related, in-progress discussions around `external-content` should be addressed prior to changing relevant elements of the spec.
#40 
#41 
#80 
#83

**Comment by acoburn** [comment]
@awoods: I disagree. All of those tickets relate to the details of the interaction model _if_ a given resource uses the `external-body` resource type. This is about whether that type is _required_ in the first place.

**Comment by acoburn** [comment]
@awoods I will also note that Trellis will _not_ be supporting external-body resources. I would assert that there are better ways to deal with "external content", and _requiring_ a pattern that is arguably of dubious quality is a bad thing to have in the spec.

**Comment by awoods** [comment]
@acoburn : Fair enough. Has there been discussion in support of the recommendation to remove the requirement of "external content" from the spec?

**Comment by acoburn** [comment]
My claim is that the _requirement_ is ambiguous in the text: POST has _should_ and PUT has _must_. That is wrong. This PR aligns the language to the less stringent level; if there should be discussion on the matter, then please open an issue.

**Pull request closed without merging**
