### PR TITLE
Add link to previous specification URL

### PR DESCRIPTION
**Pull request by awoods**
* Note: https://github.com/w3c/respec/wiki/previousURI did not render

Resolves: https://github.com/fcrepo/fcrepo-specification/issues/303

### CODE REVIEW

**Review by escowles — DISMISSED** [review]

**Review by barmintor — DISMISSED** [review]

**Comment by awoods** [comment]
This shows up as the following, which maybe is slightly incorrect/misleading:
screenshot from 2017-11-27 17-17-14

**Review by zimeon — DISMISSED** [review]

**Comment by zimeon** [comment]
A bit weird that it shows as "Latest Recommendation"... but does the job

**Comment by awoods** [comment]
Much better with: https://github.com/fcrepo/fcrepo-specification/pull/304/commits/0939f20a5b988ed40a2e735bb60ffa645d7dbbdc
@zimeon / @barmintor / @escowles : Please give it another look.

**Review by zimeon — APPROVED** [review]
Much improved :100:

**Review by escowles — APPROVED** [review]

**Comment by awoods** [comment]
@barmintor approved the previous commit. I suspect he would be more than happy to approve this one as well. 
@escowles / @zimeon : would one of you care to merge, then I will finish the release process.

**Pull request merged**
