### PR TITLE
Render small caps for MAY, MUST, SHOULD

### LINKED ISSUE #195: Capitalize MAY, MUST, SHOULD, etc in the rendered document
Doing so helps the reader understand that such statements are normative, and emphasizes the level of requirement.

### PR DESCRIPTION
**Pull request by birkland**
Changes the css so that RFC2119 terms are depicted in small caps in the
rendered document

Resolves #195

### CODE REVIEW

**Comment by acoburn** [comment]
Rather than changing the respec javascript document (which will make future updates to respec very difficult), is it not possible to change the CSS in the index.html file?

**Comment by birkland** [comment]
I can try and see what happens.

**Comment by birkland** [comment]
Hey, it looks like that works!  Thanks @acoburn

**Review by awoods — APPROVED** [review]
Along these same lines, it looks like `<code>` blocks may suffer from a similar styling flaw.

**Review by escowles — APPROVED** [review]

**Review by zimeon — APPROVED** [review]

**Review by dannylamb — APPROVED** [review]

**Comment by awoods** [comment]
@barmintor : please feel free to merge this PR.

**Pull request merged**
