### PR TITLE
Add version number to specification title

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/fcrepo/fcrepo-specification/issues/280

### CODE REVIEW

**Comment by escowles** [comment]
Do we want to label it "1.0 Candidate Recommendation" for now? I am a little hesitant to label it "1.0" until it's actually final.

**Comment by awoods** [comment]
I am happy to let this PR sit until we are ready for the release.

**Comment by zimeon** [comment]
I changed title from using 1.0.0 to say "Fedora API Specification 1.0" as we had agreed in #280/#334. I think we can close #334 that change is included here

**Comment by awoods** [comment]
Close in favor of: https://github.com/fcrepo/fcrepo-specification/pull/375

**Pull request closed without merging**
