### PR TITLE
Avoid suggesting that there should be multiple Link headers

### LINKED ISSUE #312: Clarify many links rather than many link headers
Particularly in [LDPRv GET](https://fcrepo.github.io/fcrepo-specification/#ldprv-get), it seems confusing that we list a set of "Link headers" that are required, when these are best expressed as a set of links in ONE `Link:` header.

This seems misleading/confusing. I note that in LDP the language is often similar and somewhat confusing. Although appealing, the term "link relation" is used in LDP and [RFC5988 sec4](https://tools.ietf.org/html/rfc5988#section-4) is used for the predicate, so I think talking about **links** following [RFC5988 sec3](https://tools.ietf.org/html/rfc5988#section-3) that are expressed in a `Link:` header would be the best option.

### PR DESCRIPTION
**Pull request by zimeon**
Fixes #312

### CODE REVIEW

**Comment by awoods** [comment]
Travis blues :musical_score: https://travis-ci.org/fcrepo/fcrepo-specification/builds/329738795

**Review by awoods — APPROVED** [review]

**Review by awoods — DISMISSED** [review]
Pending Travis fix

**Review by dannylamb — APPROVED** [review]
It's a subtle difference, but I think this improves readability, too.

**Comment by dannylamb** [comment]
Assuming you appease our great overlord Travis.

**Review by escowles — APPROVED** [review]

**Review by barmintor — APPROVED** [review]

**Pull request merged**
