### PR TITLE
Reflowing line lengths to be 120 characters or less.

### PR DESCRIPTION
**Pull request by escowles**
Non-functional update: reflowing text to be 120 characters or less per line.  In my browser (with generous font sizes), none of the new text is cut off in the diff display.

### CODE REVIEW

**Comment by acoburn** [comment]
Thanks @escowles! 👍

**Comment by awoods** [comment]
It could make sense to have this ensured by Travis:
https://github.com/w3c/webrtc-respec-ci

**Comment by escowles** [comment]
@awoods That looks like a good thing to add to our CI — though I don't see any MacOSX support, so it's a little hard for me to test.

**Comment by awoods** [comment]
@escowles : I suspect there are other options... maybe:
https://perlmaven.com/run-perl-tidy-to-beautify-the-code

**Comment by escowles** [comment]
Though if we just want to check for 120+ character lines (other than the overrideCopyright one), we could just do:

```
script:
- test `cut -c121- index.html | grep -vx "^$" | wc -l` -lt 2
```

**Comment by zimeon** [comment]
:+1: on these changes, :+1: on adding the 120-char travis check. I think it would also be good to have a scripted auto-format provided we can find something that isn't too ugly.

**Comment by escowles** [comment]
I've added the simple test for whether there are lines longer than 120-chars.  I agree it would be nice to have an autoformatter, though i'm not sure I like the output of tidy.  Does anybody have any other suggestions?

**Comment by barmintor** [comment]
👍

**Pull request merged**
