### PR TITLE
Require IRIs for users and groups

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/fcrepo/fcrepo-specification/issues/166

### CODE REVIEW

**Comment by acoburn** [comment]
The SOLID WAC document describes Agents like so:

> In WAC, we use the term Agent to identify who is allowed access to various resources. In general, it is assumed to mean "someone or something that can be referenced with a WebID" ....

I do not understand this to mean that "Agents MUST be described using WebIDs"; rather, I understand this to mean that WebIDs are one valid construct for describing agents. As such, I do not understand the need for the addition in this PR; I find it redundant and I do not agree that it is "a departure from the SOLIDWEBAC requirement".

**Comment by awoods** [comment]
According to the [SOLID overview](https://github.com/solid/web-access-control-spec#overview):
> 1. The resources are identified by URLs, and can refer to any web documents or resources.
> 2. It is declarative -- access control policies live in regular web documents, which can be exported/backed easily, using the same mechanism as you would for backing up the rest of your data.
> 3. Users and groups are also identified by URLs (specifically, by WebIDs)

My reading is that, specifically, WebIDs are required.
This PR is intended to clarify that WebIDs are not required, nor URLs, but rather IRIs.

**Comment by acoburn** [comment]
Given a group IRI: `info:group/foo`, which is a valid IRI (and valid according to this PR), how would an implementation follow the [SOLID guidelines](https://github.com/solid/web-access-control-spec#groups-of-agents) to dereference that group?

**Comment by acoburn** [comment]
Perhaps I should ask: what is the rationale behind departing from the SOLID specification like this? I can support declarations in the Fedora specification that are _more specific_ than in a parent specification (whether that is LDP, HTTP, etc), but stating that a requirement of a parent specification does not apply seems very problematic. It is akin to asserting that the HTTP header `Expect` can be used with 2xx responses. Doing so will weaken the Fedora specification, and I would encourage you to examine exactly why you are choosing to depart from a parent specification.

I would broadly state that I am 👎  on any such departure from a parent specification.

**Comment by awoods** [comment]
Changing this wording from `IRI` to `URL` probably makes sense.

**Comment by escowles** [comment]
Related: I have an action item to add language explictly requiring that group IRIs be resolvable, and reference members using `vcard:hasMember`.  I have added #200 to track that.

**Comment by acoburn** [comment]
@escowles doesn't that mean that Fedora requires that groups are, effectively, WebIDs (they are URLs and they can be dereferenced as RDF resources)? SOLID already requires that groups are identified as URLs and that they can be dereferenced as RDF, and so, why does Fedora need to restate something that SOLID already includes?

**Comment by acoburn** [comment]
@awoods: if WebID is a proposed W3C standard and SOLID embraces it for use with WebAC, why would Fedora explicitly _not_ use WebIDs for agents and groups? Isn't a major goal of the Fedora specification effort designed to align Fedora with other, existing web standards?

**Comment by awoods** [comment]
The intent of this PR is to clarify that although the SOLID document can be interpreted as requiring WebIDs, Fedora makes no such requirement.

**Comment by acoburn** [comment]
@awoods: and why not? I would expect at least some non-normative text explaining that decision.

**Comment by awoods** [comment]
Are you now suggesting that WebIDs be required?

**Comment by acoburn** [comment]
@awoods: I am suggesting that Fedora not depart from SOLID. If that means that Fedora requires using WebIDs, then yes, that is what I am suggesting. This does not mean that I would include text in the Fedora specification that explicitly states that agents MUST be represented by WebIDs, but I would think it would make sense to have some non-normative text referencing the SOLID specification about representing agents/groups and the importance of making those identifiers be URLs.

**Comment by escowles** [comment]
I would be fine with saying to use SOLID, but having a non-normative note saying basically what's in #200 — groups must be dereferencable and point to user URIs with `vcard:hasMember`.  That would be good explicit guidance about how we interpret SOLID and what we think is the minimum an implementation could do to be useful and valid.

**Comment by escowles** [comment]
Closing in favor of #207

**Pull request closed without merging**
